[global]
disableWidgetStateDuplicationWarning = false

[runner]
fastReruns = true
magicEnabled = false

[client]
showSidebarNavigation = false
showErrorDetails = false
toolbarMode = "minimal"

[server]
runOnSave = true
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
font="sans serif"
base="dark"
primaryColor="#d4ea0d"